CREATE SEQUENCE course_seq START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE TABLE COURSE (
   ID BIGINT PRIMARY KEY,
   CLASS_ID BIGINT NOT NULL,
   TEACHER_ID BIGINT NOT NULL,
   COURSE_NAME VARCHAR(256) NOT NULL,
   COURSE_DESC VARCHAR (256) NOT NULL
);
COMMIT;